server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaruant?useSSL=false&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: org.apache.ibatis.datasource.unpooled.UnpooledDataSource.DriverProxy