server:
  port: 8090


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaruant?useSSL=false&characterEncoding=UTF-8
    username: root
    password: admin

  jpa:
    hibernate:
#      自动创建、更新、验证数据表结构
      ddl-auto: update
#      默认的设置数据库引擎为INNODB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    打印SQL语句，方便调试
    show-sql: true
